# Generated by Django 5.1.7 on 2026-03-10 16:20

import books.models.book_photo
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=books.models.book_photo.book_photo_upload_path,
                        verbose_name="照片",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="照片說明"
                    ),
                ),
            ],
            options={
                "verbose_name": "書況照片",
                "verbose_name_plural": "書況照片",
                "db_table": "exbook_book_photo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="套書名稱")),
                ("description", models.TextField(blank=True, verbose_name="套書說明")),
            ],
            options={
                "verbose_name": "套書",
                "verbose_name_plural": "套書",
                "db_table": "exbook_book_set",
            },
        ),
        migrations.CreateModel(
            name="OfficialBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "isbn",
                    models.CharField(
                        db_index=True,
                        help_text="10 碼或 13 碼 ISBN",
                        max_length=13,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="書名")),
                (
                    "author",
                    models.CharField(blank=True, max_length=200, verbose_name="作者"),
                ),
                (
                    "publisher",
                    models.CharField(blank=True, max_length=100, verbose_name="出版社"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="book_covers/%Y/%m/",
                        verbose_name="封面圖片",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="書籍簡介")),
            ],
            options={
                "verbose_name": "官方書籍",
                "verbose_name_plural": "官方書籍",
                "db_table": "exbook_official_book",
            },
        ),
        migrations.CreateModel(
            name="SharedBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "transferability",
                    models.CharField(
                        choices=[("TRANSFER", "開放傳遞"), ("RETURN", "閱畢即還")],
                        default="RETURN",
                        max_length=10,
                        verbose_name="流通性",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "暫不開放"),
                            ("T", "可移轉"),
                            ("R", "應返還"),
                            ("V", "已被預約"),
                            ("O", "借閱中"),
                            ("E", "例外狀況"),
                            ("L", "已遺失"),
                            ("D", "已損毀"),
                        ],
                        default="S",
                        max_length=1,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "condition_description",
                    models.TextField(blank=True, verbose_name="書況描述"),
                ),
                (
                    "loan_duration_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="最少 15 天，最多 90 天",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="借閱天數",
                    ),
                ),
                (
                    "extend_duration_days",
                    models.PositiveIntegerField(
                        default=14,
                        help_text="最少 7 天，最多 30 天",
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="可延長天數",
                    ),
                ),
                (
                    "listed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上架時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "分享書籍",
                "verbose_name_plural": "分享書籍",
                "db_table": "exbook_shared_book",
            },
        ),
        migrations.CreateModel(
            name="WishListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "願望書車",
                "verbose_name_plural": "願望書車",
                "db_table": "exbook_wish_list_item",
            },
        ),
    ]
