# Generated by Django 5.2.1 on 2026-04-04 12:06

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_wishlistitem_official_book_on_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialbook',
            options={'verbose_name': '官方書目', 'verbose_name_plural': '官方書目'},
        ),
        migrations.AlterField(
            model_name='officialbook',
            name='category',
            field=models.CharField(choices=[('小說', '小說'), ('科技', '科技'), ('藝術', '藝術'), ('科學', '科學'), ('其他', '未分類')], default='其他', max_length=20, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='sharedbook',
            name='official_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_books', to='books.officialbook', verbose_name='官方書目'),
        ),
        migrations.AlterField(
            model_name='sharedbook',
            name='status',
            field=django_fsm.FSMField(choices=[('S', '暫不開放'), ('T', '可移轉'), ('R', '應返還'), ('V', '已被預約'), ('O', '借閱中'), ('E', '例外狀況'), ('L', '已遺失'), ('D', '已損毀')], default='S', max_length=1, verbose_name='狀態'),
        ),
        migrations.AddIndex(
            model_name='sharedbook',
            index=models.Index(fields=['-listed_at'], name='idx_listed_at_desc'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['official_book'], name='idx_official_book'),
        ),
    ]
