# Generated by Django 5.2.1 on 2026-04-15 03:41
# pyright: reportArgumentType=false

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_officialbook_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedbook",
            name="min_trust_level",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="申請者信用等級需達 0-3，0 表示不限制",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="最低信用等級",
            ),
        ),
    ]
