# Generated by Django 5.1.7 on 2026-03-10 16:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "deal_type",
                    models.CharField(
                        choices=[
                            ("LN", "借用交易"),
                            ("RS", "返還交易"),
                            ("TF", "傳遞交易"),
                            ("RG", "回歸交易"),
                            ("EX", "例外處理"),
                        ],
                        max_length=2,
                        verbose_name="交易類別",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Q", "已請求"),
                            ("P", "已回應"),
                            ("M", "已面交"),
                            ("D", "已完成"),
                            ("X", "已取消"),
                        ],
                        default="Q",
                        max_length=1,
                        verbose_name="交易狀態",
                    ),
                ),
                (
                    "previous_book_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "暫不開放"),
                            ("T", "可移轉"),
                            ("R", "應返還"),
                            ("V", "已被預約"),
                            ("O", "借閱中"),
                            ("E", "例外狀況"),
                            ("L", "已遺失"),
                            ("D", "已損毀"),
                        ],
                        help_text="用於取消交易時恢復書籍狀態（BR-14）",
                        max_length=1,
                        verbose_name="交易前書籍狀態",
                    ),
                ),
                (
                    "meeting_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="面交地點"
                    ),
                ),
                (
                    "meeting_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="面交時間"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="僅 LN/TF 類型交易需要",
                        null=True,
                        verbose_name="到期日",
                    ),
                ),
                (
                    "applicant_rated",
                    models.BooleanField(default=False, verbose_name="申請者已評價"),
                ),
                (
                    "responder_rated",
                    models.BooleanField(default=False, verbose_name="回應者已評價"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
                (
                    "book_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="若為套書交易，關聯至套書",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="books.bookset",
                        verbose_name="套書",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responded_deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回應者",
                    ),
                ),
                (
                    "shared_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="books.sharedbook",
                        verbose_name="交易書籍",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易",
                "verbose_name_plural": "交易",
                "db_table": "exbook_deal",
            },
        ),
        migrations.CreateModel(
            name="DealMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                ("content", models.TextField(verbose_name="訊息內容")),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="deals.deal",
                        verbose_name="交易",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_deal_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易留言",
                "verbose_name_plural": "交易留言",
                "db_table": "exbook_deal_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "extra_days",
                    models.PositiveIntegerField(
                        help_text="最少 7 天，最多 30 天",
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="延長天數",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待審核"),
                            ("APPROVED", "已核准"),
                            ("REJECTED", "已拒絕"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="申請狀態",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_extensions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="審核者",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="deals.deal",
                        verbose_name="交易",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_extensions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
            ],
            options={
                "verbose_name": "延長申請",
                "verbose_name_plural": "延長申請",
                "db_table": "exbook_loan_extension",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("DEAL_REQUESTED", "收到交易申請"),
                            ("DEAL_RESPONDED", "交易已被回應"),
                            ("DEAL_CANCELLED", "交易被取消"),
                            ("DEAL_MEETED", "面交完成，請評價"),
                            ("BOOK_DUE_SOON", "書籍即將到期"),
                            ("BOOK_OVERDUE", "書籍已逾期"),
                            ("BOOK_AVAILABLE", "願望書籍已可借閱"),
                            ("EXTEND_REQUESTED", "收到延長申請"),
                            ("EXTEND_APPROVED", "延長申請已核准"),
                            ("EXTEND_REJECTED", "延長申請已拒絕"),
                        ],
                        max_length=20,
                        verbose_name="通知類型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="通知標題")),
                ("message", models.TextField(blank=True, verbose_name="通知訊息")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已讀"),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="deals.deal",
                        verbose_name="相關交易",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
                (
                    "shared_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="books.sharedbook",
                        verbose_name="相關書籍",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "exbook_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "integrity_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="誠信評分",
                    ),
                ),
                (
                    "punctuality_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="準時評分",
                    ),
                ),
                (
                    "accuracy_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="書況準確度評分",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="評語")),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ratings",
                        to="deals.deal",
                        verbose_name="交易",
                    ),
                ),
                (
                    "ratee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被評價者",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="given_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="評價者",
                    ),
                ),
            ],
            options={
                "verbose_name": "評價",
                "verbose_name_plural": "評價",
                "db_table": "exbook_rating",
            },
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["applicant", "status"], name="exbook_deal_applica_b1c972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["responder", "status"], name="exbook_deal_respond_8ee5c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["shared_book", "status"], name="exbook_deal_shared__f775da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["due_date"], name="exbook_deal_due_dat_e4fcd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="exbook_noti_recipie_901851_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("deal", "rater"), name="unique_deal_rater"
            ),
        ),
    ]
