# Generated by Django 5.2.1 on 2026-03-18 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPushConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "vapid_public_key",
                    models.CharField(
                        help_text="用於前端註冊 Push 訂閱",
                        max_length=100,
                        verbose_name="VAPID 公開金鑰",
                    ),
                ),
                (
                    "vapid_private_key",
                    models.TextField(
                        help_text="用於後端發送 Push 通知（請勿洩漏）",
                        verbose_name="VAPID 私有金鑰",
                    ),
                ),
                (
                    "subject",
                    models.URLField(
                        blank=True,
                        help_text="聯絡信箱或網站 URL（mailto: 或 https://）",
                        verbose_name="主體",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Push 設定",
                "verbose_name_plural": "Web Push 設定",
                "db_table": "exbook_web_push_config",
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "endpoint",
                    models.URLField(
                        help_text="Push 服務的唯一端點 URL",
                        max_length=500,
                        verbose_name="訂閱端點",
                    ),
                ),
                (
                    "p256dh",
                    models.CharField(
                        help_text="用戶端的公開金鑰（ECDH P-256）",
                        max_length=100,
                        verbose_name="p256dh 金鑰",
                    ),
                ),
                (
                    "auth",
                    models.CharField(
                        help_text="認證金鑰（16 bytes base64 編碼）",
                        max_length=30,
                        verbose_name="auth 金鑰",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="瀏覽器識別資訊",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="停用後將不會收到 Push 通知",
                        verbose_name="是否啟用",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push 訂閱",
                "verbose_name_plural": "Push 訂閱",
                "db_table": "exbook_push_subscription",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="exbook_push_user_id_fa806c_idx",
                    ),
                    models.Index(
                        fields=["endpoint"], name="exbook_push_endpoin_fc373c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("endpoint",), name="unique_endpoint"
                    )
                ],
            },
        ),
    ]
