# Generated by Django 5.2.1 on 2026-04-03 15:49

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


def forwards_copy_approved_by(apps, schema_editor):
    LoanExtension = apps.get_model("deals", "LoanExtension")

    for extension in LoanExtension.objects.select_related(
        "deal__shared_book", "approved_by"
    ):
        reviewer = extension.approved_by
        if reviewer is None:
            continue

        shared_book = extension.deal.shared_book
        update_fields = []

        if reviewer_id_equals(reviewer, shared_book.owner):
            extension.owner_approved_by = reviewer
            update_fields.append("owner_approved_by")

        if reviewer_id_equals(reviewer, shared_book.keeper):
            extension.keeper_approved_by = reviewer
            update_fields.append("keeper_approved_by")

        if update_fields:
            extension.save(update_fields=update_fields)


def backwards_copy_approved_by(apps, schema_editor):
    LoanExtension = apps.get_model("deals", "LoanExtension")

    for extension in LoanExtension.objects.select_related(
        "owner_approved_by",
        "keeper_approved_by",
    ):
        reviewer = extension.owner_approved_by or extension.keeper_approved_by
        if reviewer is None:
            continue
        extension.approved_by = reviewer
        extension.save(update_fields=["approved_by"])


def reviewer_id_equals(user_a, user_b):
    if user_a is None or user_b is None:
        return False
    return user_a.pk == user_b.pk


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0003_add_appeal_notification_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loanextension",
            name="keeper_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="keeper_reviewed_extensions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Keeper 審核者",
            ),
        ),
        migrations.AddField(
            model_name="loanextension",
            name="owner_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_reviewed_extensions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner 審核者",
            ),
        ),
        migrations.RunPython(
            code=forwards_copy_approved_by,
            reverse_code=backwards_copy_approved_by,
        ),
        migrations.RemoveField(
            model_name="loanextension",
            name="approved_by",
        ),
        migrations.AlterField(
            model_name="loanextension",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "待審核"),
                    ("PARTIALLY_APPROVED", "部分核准"),
                    ("APPROVED", "已核准"),
                    ("REJECTED", "已拒絕"),
                ],
                default="PENDING",
                max_length=18,
                protected=True,
                verbose_name="申請狀態",
            ),
        ),
    ]
