# Generated by Django 5.2.1 on 2026-04-04 12:06

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_officialbook_options_and_more"),
        ("deals", "0005_rename_integrity_score_to_friendliness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanextension",
            name="keeper_approved_by",
        ),
        migrations.RemoveField(
            model_name="loanextension",
            name="owner_approved_by",
        ),
        migrations.AddField(
            model_name="loanextension",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_extensions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="審核者",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("Q", "已請求"),
                    ("P", "已回應"),
                    ("M", "已面交"),
                    ("D", "已完成"),
                    ("X", "已取消"),
                ],
                default="Q",
                max_length=1,
                protected=True,
                verbose_name="交易狀態",
            ),
        ),
        migrations.AlterField(
            model_name="loanextension",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "待審核"),
                    ("APPROVED", "已核准"),
                    ("REJECTED", "已拒絕"),
                ],
                default="PENDING",
                max_length=10,
                protected=True,
                verbose_name="申請狀態",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["-created_at"], name="idx_created_at_desc"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "notification_type"], name="idx_recipient_type"
            ),
        ),
    ]
