# Generated by Django 5.2.1 on 2026-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0006_remove_loanextension_keeper_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("DEAL_REQUESTED", "收到交易申請"),
                    ("DEAL_RESPONDED", "交易已被回應"),
                    ("DEAL_CANCELLED", "交易被取消"),
                    ("DEAL_MEETED", "面交完成，請評價"),
                    ("BOOK_DUE_SOON", "書籍即將到期"),
                    ("BOOK_OVERDUE", "書籍已逾期"),
                    ("BOOK_AVAILABLE", "願望書籍已可借閱"),
                    ("EXTEND_REQUESTED", "收到延長申請"),
                    ("EXTEND_APPROVED", "延長申請已核准"),
                    ("EXTEND_REJECTED", "延長申請已拒絕"),
                    ("APPEAL_SUBMITTED", "申訴已送出"),
                    ("APPEAL_RESOLVED", "申訴審核完成"),
                    ("RATING_CREATED", "收到新的評價"),
                    ("VIOLATION_CREATED", "收到違規處分"),
                    ("APPEAL_STATUS_UPDATED", "申訴狀態更新"),
                ],
                max_length=50,
                verbose_name="通知類型",
            ),
        ),
    ]
