# Generated by Django 5.2.1 on 2026-03-14 13:50

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    def get_perm(app_label, model_name, codename):
        ct, _ = ContentType.objects.get_or_create(
            app_label=app_label,
            model=model_name.lower(),
        )
        perm, _ = Permission.objects.get_or_create(
            content_type=ct,
            codename=codename,
            defaults={"name": codename.replace("_", " ").title()},
        )
        return perm

    # Group 1: 客服人員
    cs_group, _ = Group.objects.get_or_create(name="客服人員")
    cs_perms = [
        ("deals", "deal", "view_deal"),
        ("deals", "dealmessage", "view_dealmessage"),
        ("deals", "loanextension", "view_loanextension"),
        ("deals", "notification", "view_notification"),
        ("books", "officialbook", "view_officialbook"),
        ("books", "bookset", "view_bookset"),
        ("books", "sharedbook", "view_sharedbook"),
        ("auth", "user", "view_user"),
    ]
    for app, model, code in cs_perms:
        cs_group.permissions.add(get_perm(app, model, code))

    # Group 2: 內容管理員
    ca_group, _ = Group.objects.get_or_create(name="內容管理員")
    ca_perms = [
        ("books", "officialbook", "view_officialbook"),
        ("books", "officialbook", "add_officialbook"),
        ("books", "officialbook", "change_officialbook"),
        ("books", "officialbook", "delete_officialbook"),
        ("books", "bookset", "view_bookset"),
        ("books", "bookset", "add_bookset"),
        ("books", "bookset", "change_bookset"),
        ("books", "bookset", "delete_bookset"),
        ("books", "sharedbook", "view_sharedbook"),
    ]
    for app, model, code in ca_perms:
        ca_group.permissions.add(get_perm(app, model, code))


def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["客服人員", "內容管理員"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("books", "0002_initial"),
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
