# Generated by Django 5.2.1 on 2026-03-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='overdue_count',
            field=models.IntegerField(default=0, verbose_name='逾期次數'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='successful_returns',
            field=models.IntegerField(default=0, verbose_name='成功歸還次數'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trust_level',
            field=models.IntegerField(default=1, help_text='0: 新手, 1: 一般, 2: 可信, 3: 優良', verbose_name='信用等級'),
        ),
    ]
