# Generated by Django 5.2.1 on 2026-03-24 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userprofile_overdue_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "appeal_type",
                    models.CharField(
                        choices=[
                            ("account_suspension", "帳號停權申訴"),
                            ("rating_dispute", "評價爭議"),
                            ("overdue_dispute", "逾期爭議"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="申訴類型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "evidence",
                    models.FileField(
                        blank=True, upload_to="appeals/%Y/%m/", verbose_name="證據文件"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "已提交"),
                            ("under_review", "審核中"),
                            ("approved", "已通過"),
                            ("rejected", "已駁回"),
                            ("closed", "已結案"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="審核備註"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="審核時間"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_appeals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="審核者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申訴人",
                    ),
                ),
            ],
            options={
                "verbose_name": "申訴",
                "verbose_name_plural": "申訴",
                "db_table": "exbook_appeal",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="exbook_appe_user_id_4bbdcb_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="exbook_appe_status_d7a86a_idx",
                    ),
                ],
            },
        ),
    ]
