# Generated by Django 5.2.1 on 2026-03-29 02:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_add_appeal_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="用戶目前是否處於停權狀態",
                verbose_name="是否停權中",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="suspension_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="暫時停權的結束時間，null 表示永久停權",
                null=True,
                verbose_name="停權結束時間",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="suspension_reason",
            field=models.TextField(blank=True, verbose_name="停權原因"),
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("warning", "警告"),
                            ("temporary_suspension", "暫時停權"),
                            ("permanent_suspension", "永久停權"),
                        ],
                        max_length=30,
                        verbose_name="處分類型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "輕微"),
                            ("moderate", "中等"),
                            ("severe", "嚴重"),
                        ],
                        max_length=20,
                        verbose_name="違規等級",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("missed_meeting", "未依約定面交"),
                            ("late_return", "延遲歸還"),
                            ("condition_mismatch", "書況描述不符"),
                            ("unjustified_cancellation", "無正當理由取消"),
                            ("fraud", "詐欺"),
                            ("harassment", "騷擾"),
                            ("malicious_damage", "惡意破壞"),
                            ("identity_theft", "冒用身份"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="違規行為",
                    ),
                ),
                ("description", models.TextField(verbose_name="違規描述")),
                (
                    "suspension_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="暫時停權時必填，7-30 天",
                        null=True,
                        verbose_name="停權天數",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="警告永遠生效；停權在期滿或解除後設為 False",
                        verbose_name="是否生效中",
                    ),
                ),
                (
                    "lifted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解除時間"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_violations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="處分者",
                    ),
                ),
                (
                    "lifted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifted_violations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="解除者",
                    ),
                ),
                (
                    "related_appeal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="violations",
                        to="accounts.appeal",
                        verbose_name="相關申訴",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="違規用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "違規處分",
                "verbose_name_plural": "違規處分",
                "db_table": "exbook_violation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="exbook_viol_user_id_1f1f91_idx",
                    ),
                    models.Index(
                        fields=["action_type", "is_active"],
                        name="exbook_viol_action__ea2f37_idx",
                    ),
                ],
            },
        ),
    ]
