# Generated by Django 5.2.1 on 2026-04-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_violation_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="trust_score",
            field=models.IntegerField(default=0, verbose_name="信用積分"),
        ),
    ]
