# Generated by Django 5.2.1 on 2026-04-05 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_appeal_status_alter_userprofile_trust_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="trust_level",
        ),
    ]
