# Generated by Django 5.2.1 on 2026-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_userprofile_trust_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustLevelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(unique=True, verbose_name="等級"),
                ),
                (
                    "group_name",
                    models.CharField(max_length=50, verbose_name="對應群組名稱"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=50, verbose_name="顯示名稱"),
                ),
                ("min_score", models.IntegerField(verbose_name="最低積分門檻")),
                (
                    "max_books",
                    models.PositiveSmallIntegerField(verbose_name="最大持書數量"),
                ),
                (
                    "max_days",
                    models.PositiveSmallIntegerField(verbose_name="最大借閱天數"),
                ),
                (
                    "demotion_protection_weeks",
                    models.PositiveSmallIntegerField(
                        default=26,
                        help_text="達到此等級後的保護期限，期間內若積分不足也不會降級",
                        verbose_name="降級保護週數",
                    ),
                ),
                (
                    "badge_icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS class 或圖片路徑",
                        max_length=100,
                        verbose_name="徽章圖標",
                    ),
                ),
            ],
            options={
                "verbose_name": "信用等級配置",
                "verbose_name_plural": "信用等級配置",
                "db_table": "exbook_trust_level_config",
                "ordering": ["level"],
            },
        ),
    ]
