#!/usr/bin/env python3
"""Fill in PO file translations for zh_Hant (passthrough), en (English), and ko (Korean)."""

import polib
import re

ZH_HANT_PO = "locale/zh_Hant/LC_MESSAGES/django.po"
EN_PO = "locale/en/LC_MESSAGES/django.po"
KO_PO = "locale/ko/LC_MESSAGES/django.po"


def fill_zh_hant():
    """zh_Hant: copy msgid to msgstr (source is already Chinese)."""
    po = polib.pofile(ZH_HANT_PO)
    count = 0
    for entry in po:
        if entry.msgid and not entry.msgstr:
            entry.msgstr = entry.msgid
            count += 1
    po.save()
    print(f"zh_Hant: filled {count} translations")


def translate_chinese_to_english(text: str) -> str:
    """Translate a Chinese string to English using patterns + dictionary."""
    # Simple patterns
    if text.startswith("Exbooks") and not re.search(r'[\u4e00-\u9fff\u3000-\u303f\uff00-\uffef]', text):
        return text  # Already English (no CJK chars)
    if text.startswith("CSS"):
        return text
    if text.startswith("Google"):
        return text
    if text.startswith("User"):
        return text
    if text.startswith("Back to"):
        return text  # Already English
    if text == "English":
        return "English"
    if text == "Email":
        return "Email"
    if text == "Confirm":
        return "Confirm"
    if text == "ISBN":
        return "ISBN"
    if text == "Sign In":
        return "Sign In"
    if text == "Sign Up":
        return "Sign Up"

    # Django admin / allauth strings that are already partially English
    if "Confirmation" in text or "Verify" in text:
        return text

    # Large translation dict
    translations = {
        # Login / Registration
        "Email": "Email",
        "密碼": "Password",
        "登入": "Log In",
        "暱稱": "Nickname",
        "顯示在平台上的名稱": "Display Name",
        "出生日期": "Date of Birth",
        "用於年齡驗證（需年滿 18 歲）": "For age verification (must be 18+)",
        "再次確認密碼": "Confirm Password",
        "你的暱稱": "Your Nickname",
        "註冊": "Register",
        "預設取書地點": "Default Meetup Location",
        "例如：台北市大安區": "e.g., Da'an District, Taipei",
        "完成註冊": "Complete Registration",
        "儲存並繼續": "Save & Continue",
        "完善個人資料": "Complete Profile",
        "立即免費註冊": "Register Free Now",
        
        # Violation types
        "輕微": "Minor",
        "中等": "Medium",
        "嚴重": "Severe",
        "警告": "Warning",
        "暫時停權": "Temporary Suspension",
        "永久停權": "Permanent Ban",
        "未依約定面交": "Missed Meetup",
        "延遲歸還": "Late Return",
        "書況描述不符": "Book Condition Mismatch",
        "無正當理由取消": "Unjustified Cancellation",
        "詐欺": "Fraud",
        "騷擾": "Harassment",
        "惡意破壞": "Malicious Damage",
        "冒用身份": "Identity Theft",
        "其他": "Other",
        
        # Violation management
        "違規用戶": "Violating User",
        "處分類型": "Penalty Type",
        "違規等級": "Violation Level",
        "違規行為": "Violation Type",
        "違規描述": "Description",
        "停權天數": "Suspension Days",
        "暫時停權時必填，7-30 天": "Required for temporary suspension, 7-30 days",
        "是否生效中": "Active",
        "警告永遠生效；停權在期滿或解除後設為 False": "Warning is permanent; suspension set to False after expiry",
        "相關申訴": "Related Appeals",
        "違規次數": "Violation Count",
        "處分者": "Issued By",
        "違規處分": "Violation Penalty",
        "限制中": "Restricted",
        "部分功能受限": "Some Features Restricted",
        "等級保護起始時間": "Level Protection Start",
        "降級保護週數": "Demotion Protection (Weeks)",
        "記錄用戶積分跌破門檻後，降級保護期開始計時的時間點": "Timestamp when demotion protection started after score dropped below threshold",
        "達到此等級後的保護期限，期間內若積分不足也不會降級": "Protection period after reaching this level; won't be demoted even if score drops",
        "對應群組名稱": "Corresponding Group Name",
        "等級": "Level",
        "當下等級（0-3）": "Current Level (0-3)",
        "當下積分": "Current Score",
        "用戶的信用積分，根據交易、評價、逾期等計算": "User trust score, calculated from deals, ratings, overdue records",
        "用戶目前是否處於停權狀態": "Whether the user is currently suspended",
        "最低信用等級": "Minimum Trust Level",
        "最低積分門檻": "Minimum Score Threshold",
        "申請者信用等級需達 0-3，0 表示不限制": "Applicant trust level must be 0-3 (0 = no restriction)",
        "公式版本": "Formula Version",
        "基準": "Baseline",
        "批次／手動重算": "Batch / Manual Recalculate",
        "詳情": "Details",
        "解除時間": "Unlock Time",
        "解除者": "Unlocked By",
        "信用積分": "Trust Score",
        "信用積分稽核": "Trust Score Audit",
        "信用等級配置": "Trust Level Config",
        "信用評價機制": "Trust & Rating System",
        "角色": "Role",
        "操作者": "Operator",
        
        # Notifications
        "通知": "Notifications",
        "通知中心": "Notification Center",
        "通知標題": "Notification Title",
        "通知訊息": "Notification Message",
        "通知類型": "Notification Type",
        "是否已讀": "Read",
        "收到交易申請": "New Deal Request",
        "收到延長申請": "New Extension Request",
        "收到新的評價": "New Rating Received",
        "收到評價": "Rating Received",
        "收到違規處分": "Violation Issued",
        "啟用 Email 通知": "Enable Email Notifications",
        "啟用推播通知": "Enable Push Notifications",
        "停用後將不會收到 Push 通知": "Push notifications will be disabled",
        "關閉後將不會收到 Email 通知": "Email notifications will be disabled",
        "關閉後將不會收到瀏覽器 Push 通知": "Browser push notifications will be disabled",
        "設定": "Settings",
        "帳號設定": "Account Settings",
        "發送者": "Sender",
        
        # Push subscription
        "Push 訂閱": "Push Subscription",
        "Push 服務的唯一端點 URL": "Push Service Endpoint URL",
        "訂閱端點": "Subscription Endpoint",
        "p256dh 金鑰": "p256dh Key",
        "auth 金鑰": "auth Key",
        "認證金鑰（16 bytes base64 編碼）": "Auth Key (16 bytes base64 encoded)",
        "用戶端的公開金鑰（ECDH P-256）": "Client Public Key (ECDH P-256)",
        "VAPID 公開金鑰": "VAPID Public Key",
        "VAPID 私有金鑰": "VAPID Private Key",
        "Web Push 設定": "Web Push Settings",
        "瀏覽器識別資訊": "Browser User Agent",
        "User Agent": "User Agent",
        "用於前端註冊 Push 訂閱": "Used for frontend Push subscription registration",
        "用於後端發送 Push 通知（請勿洩漏）": "Used for backend Push notifications (do not leak)",
        "用於取消交易時恢復書籍狀態（BR-14）": "Used to restore book status when cancelling a deal (BR-14)",
        
        # Appeal system
        "申訴": "Appeal",
        "申訴人": "Appellant",
        "申訴類型": "Appeal Type",
        "申訴詳情": "Appeal Details",
        "申訴已送出": "Appeal Submitted",
        "申訴狀態更新": "Appeal Status Updated",
        "申訴審核完成": "Appeal Reviewed",
        "審核中": "Under Review",
        "審核備註": "Review Notes",
        "審核時間": "Review Time",
        "審核結果": "Review Result",
        "審核者": "Reviewed By",
        "提交申訴": "Submit Appeal",
        "取消申訴": "Cancel Appeal",
        "您尚未提交任何申訴": "You haven't submitted any appeals yet",
        "尚無申訴紀錄": "No appeal records",
        "帳號停權申訴": "Account Suspension Appeal",
        "已通過": "Approved",
        "已駁回": "Rejected",
        "由 %(email)s 於 %(date)s 審核": "Reviewed by %(email)s on %(date)s",
        "否": "No",
        "是": "Yes",
        "是（使用者已遭停權）": "Yes (User is suspended)",
        
        # Books
        "書籍": "Book",
        "書籍簡介": "About This Book",
        "書籍詳情": "Book Details",
        "書名": "Title",
        "作者": "Author",
        "作者（正規化）": "Author (Normalized)",
        "出版社": "Publisher",
        "出版社（正規化）": "Publisher (Normalized)",
        "譯者": "Translator",
        "ISBN": "ISBN",
        "10 碼或 13 碼 ISBN": "10 or 13 digit ISBN",
        "分類": "Category",
        "全部分類": "All Categories",
        "小說": "Fiction",
        "科學": "Science",
        "科技": "Technology",
        "藝術": "Art",
        "文學": "Literature",
        "歷史": "History",
        "哲學": "Philosophy",
        "一般": "General",
        "未分類": "Uncategorized",
        "封面圖片": "Cover Image",
        "預設封面": "Default Cover",
        "書況描述": "Condition Description",
        "書況照片": "Condition Photos",
        "流通性": "Availability Type",
        "預設流通性": "Default Availability",
        "開放傳遞": "Open Transfer",
        "閱畢即還": "Return After Reading",
        "可移轉": "Transferable",
        "自由流通": "Free Circulation",
        "無借閱限制": "No Borrowing Limits",
        "暫不開放": "Not Available",
        "目前尚未上傳書況照片。": "No condition photos uploaded yet.",
        "狀態：": "Status:",
        "上架時間": "Listed Date",
        "上架閒置書籍": "List Idle Books",
        "上架第一本書": "List Your First Book",
        "新增分享書籍": "Add Shared Book",
        "新增書籍": "Add Book",
        "貢獻書籍": "Contribute Books",
        "分享書籍": "Share Book",
        "探索社群好書": "Discover Community Books",
        "開始探索書籍": "Start Exploring Books",
        "所有書籍": "All Books",
        "探索": "Explore",
        "搜尋 ISBN、書名、作者、出版社": "Search ISBN, title, author, publisher",
        "搜尋書籍": "Search Books",
        "查詢中…": "Searching…",
        "排序": "Sort",
        "排序鍵": "Sort Key",
        "空白時以顯示名稱小寫排序": "Lowercase display name used when blank",
        "顯示名稱": "Display Name",
        "名稱": "Name",
        "新視界": "New Horizon",
        "刪除": "Delete",
        "刪除書籍": "Delete Book",
        "確定要刪除這本書嗎？此操作無法復原。": "Are you sure you want to delete this book? This cannot be undone.",
        "確定要刪除這張照片嗎？": "Are you sure you want to delete this photo?",
        "編輯": "Edit",
        "編輯書籍資訊": "Edit Book Info",
        "儲存變更": "Save Changes",
        "查看書籍詳情": "View Book Details",
        "上傳照片": "Upload Photos",
        "照片": "Photos",
        "照片說明": "Photo Description",
        "上傳者": "Uploaded By",
        "分享失敗，請手動複製網址": "Share failed, please copy the URL manually",
        "已複製分享連結": "Share link copied",
        "我想分享這本書給你：%(title)s": "I want to share this book with you: %(title)s",
        
        # Official book
        "官方書目": "Official Bibliography",
        "書目作者關聯": "Book-Author Association",
        "預設流通性": "Default Availability",
        
        # Book set
        "套書": "Book Set",
        "套書名稱": "Book Set Name",
        "套書說明": "Description",
        "套書書籍 <span class=\"text-primary ml-1\">(%(count)s)</span>": "Books in Set <span class=\"text-primary ml-1\">(%(count)s)</span>",
        "建立套書": "Create Book Set",
        "管理套書": "Manage Book Sets",
        "我的套書": "My Book Sets",
        "此書籍為套書的一部分，借閱時需整套借出": "This book is part of a set; the entire set must be borrowed together",
        "所屬套書": "Part of Set",
        "最多借 %(max_books)s 本，最長 %(max_days)s 天": "Max %(max_books)s books, %(max_days)s days",
        "最大借閱天數": "Max Borrow Days",
        "最大持書數量": "Max Holding Count",
        
        # Wishlist
        "願望書車": "Wishlist",
        "願望清單": "Wishlist",
        "願望書籍已可借閱": "Wishlisted book is now available",
        "想看什麼書？": "What book are you looking for?",
        
        # Deal / Trading
        "交易": "Deal",
        "交易管理": "Deal Management",
        "交易詳情": "Deal Details",
        "交易申請": "Deal Request",
        "交易狀態": "Deal Status",
        "交易狀態進度": "Deal Status Progress",
        "交易類別": "Deal Type",
        "交易類型": "Deal Type",
        "交易夥伴": "Deal Partner",
        "交易書籍": "Deal Book",
        "交易留言": "Deal Messages",
        "交易紀錄": "Deal History",
        "交易結案": "Deal Closed",
        "交易結案（DONE）": "Deal Closed (DONE)",
        "交易被取消": "Deal Cancelled",
        "交易與信用統計": "Deal & Trust Statistics",
        "交易前書籍狀態": "Pre-Deal Book Status",
        "接受申請": "Accept Request",
        "婉拒": "Decline",
        "申請交易": "Request Deal",
        "申請借用": "Request Borrow",
        "申請傳遞": "Request Transfer",
        "申請回歸": "Request Return",
        "申請返還": "Request Return",
        "申請者": "Applicant",
        "申請資訊": "Application Info",
        "申請須知": "Application Guidelines",
        "申請取消": "Cancel Request",
        "取消借閱申請": "Cancel Borrow Request",
        "申請例外處理": "Request Exception",
        "例外狀況": "Exception",
        "例外處理": "Exception Handling",
        "例外處理 (EX)": "Exception Handling (EX)",
        "提交申請後，持書人將收到通知": "The book holder will be notified after you submit",
        "想跟對方說什麼？": "Any message for the other party?",
        "對方接受後，您可與持書人協商面交時間地點": "After acceptance, you can arrange meetup with the holder",
        "同一本書的多筆申請": "Multiple applications for the same book",
        "需要您處理的申請": "Pending Your Response",
        "進行中的請求": "Active Requests",
        "有 %(count)s 本書籍收到多筆申請，建議檢視後一併處理": "%(count)s books have multiple requests — review and process them together",
        "送出申請": "Submit Request",
        "新增申請": "New Request",
        "查看資料": "View Profile",
        "前往評價": "Go to Rating",
        "完成交易": "Complete Deal",
        "完成交易進度": "Deal Progress",
        "確認新增": "Confirm Add",
        "確認歸還／上架": "Confirm Return / Re-list",
        "確認歸還並重新上架": "Confirm Return & Re-list",
        "確認面交完成": "Confirm Meetup Complete",
        "面交完成": "Meetup Complete",
        "面交完成，請評價": "Meetup Complete — Please Rate",
        
        # Deal status
        "已請求": "Requested",
        "已回應": "Responded",
        "已面交": "Met Up",
        "已結案": "Closed",
        "已取消": "Cancelled",
        "已完成": "Completed",
        "已拒絕": "Rejected",
        "已提交": "Submitted",
        "已核准": "Approved",
        "已駁回": "Rejected",
        "已通過": "Approved",
        "已毀損": "Damaged",
        "已遺失": "Lost",
        "已逾期": "Overdue",
        "已讀": "Read",
        "待評價": "Pending Rating",
        "待回應": "Pending Response",
        "待審核": "Pending Review",
        "待面交": "Pending Meetup",
        "待對方回應": "Awaiting Response",
        "已被預約": "Reserved",
        "進行中": "In Progress",
        "未知": "Unknown",
        "面交地點": "Meetup Location",
        "面交時間": "Meetup Time",
        "預計借閱天數：%(days)s 天": "Expected borrow duration: %(days)s days",
        "天": "days",
        "本": "volumes",
        "最少 15 天，最多 90 天": "Minimum 15 days, maximum 90 days",
        "最少 7 天，最多 30 天": "Minimum 7 days, maximum 30 days",
        "取書地點": "Pickup Location",
        "可取書時間": "Available Pickup Times",
        "格式: [{\"weekday\": 1, \"start\": \"09:00\", \"end\": \"12:00\"}, ...]": "Format: [{\"weekday\": 1, \"start\": \"09:00\", \"end\": \"12:00\"}, ...]",
        
        # Deal types
        "借用交易": "Borrow Deal",
        "借用交易 (LN)": "Borrow Deal (LN)",
        "借閱中": "Currently Borrowed",
        "借閱天數": "Borrow Days",
        "借閱次數": "Borrow Count",
        "借閱書籍，閱畢後歸還給持書人": "Borrow a book, return to holder after reading",
        "傳遞交易": "Transfer Deal",
        "傳遞交易 (TF)": "Transfer Deal (TF)",
        "回歸交易": "Return Deal",
        "回歸交易 (RG)": "Return Deal (RG)",
        "返還交易": "Return Deal",
        "返還交易 (RS)": "Return Deal (RS)",
        "僅 LN/TF 類型交易需要": "Only required for LN/TF type deals",
        "若為套書交易，關聯至套書": "Link to book set if applicable",
        
        # Deal process
        "線下面交": "In-Person Meetup",
        "雙方在約定的時間地點碰面交書。確認書況無誤後，在平台上點擊「已面交」。": "Meet at the agreed time and place. Confirm book condition, then tap 'Met Up' on the platform.",
        "面交時請確認書況，並在系統中完成確認": "Check book condition at meetup, then confirm in the system",
        "面交時拍攝的照片關聯至交易": "Photos taken at meetup are linked to the deal",
        "留言溝通": "Send a Message",
        "發送訊息": "Send Message",
        "歷史留言紀錄": "Message History",
        "輸入訊息": "Type a message…",
        "訊息內容": "Message Content",
        "相關書籍": "Related Books",
        "相關交易": "Related Deals",
        
        # Rating
        "評價": "Rating",
        "給出評價": "Leave a Rating",
        "評價送出": "Rating Submitted",
        "評價爭議": "Rating Dispute",
        "評價者": "Rater",
        "被評價者": "Rated User",
        "評語": "Comment",
        "雙方完成互評": "Both Parties Have Rated",
        "雙向評價": "Two-Way Rating",
        "提示：待雙方評價完成後，主按鈕才會開啟": "Note: The main button will unlock after both parties have rated",
        "提示：即便對方尚未評價，主人仍可先點擊下方「確認歸還」。": "Note: You can confirm return even if the other party hasn't rated yet",
        "平均評價": "Average Rating",
        "友善評分": "Friendliness Score",
        "書況準確度評分": "Condition Accuracy Score",
        "準時評分": "Punctuality Score",
        
        # Overdue
        "逾期次數": "Overdue Count",
        "逾期爭議": "Overdue Dispute",
        "逾期處理": "Overdue Handling",
        "到期日": "Due Date",
        "書籍即將到期": "Book Due Soon",
        "書籍已逾期": "Book Overdue",
        "到期排程處理": "Scheduled Overdue Processing",
        "公開逾期名單": "Public Overdue List",
        "強制確認歸還": "Force Confirm Return",
        
        # Extension
        "延期申請紀錄": "Extension Request History",
        "延長申請": "Extension Request",
        "延長核准": "Extension Approved",
        "延長拒絕": "Extension Denied",
        "延長取消": "Extension Cancelled",
        "延長申請已核准": "Extension Approved",
        "延長申請已拒絕": "Extension Denied",
        "延長天數": "Extension Days",
        "可延長天數": "Allowable Extension Days",
        "最少 7 天，最多 30 天": "Minimum 7 days, maximum 30 days",
        
        # Exchange event
        "交換事件": "Exchange Event",
        "事件類型": "Event Type",
        "持有者變更": "Holder Changed",
        "歸還書籍給貢獻者": "Return Book to Owner",
        "主人確認歸還書籍": "Owner Confirmed Return",
        "貢獻者取回書籍": "Owner Retrieved Book",
        "強制確認歸還": "Force Confirm Return",
        "書籍傳遞給下一位讀者": "Book Passed to Next Reader",
        "確認歸還並重新上架": "Confirm Return & Re-list",
        "應返還": "Due for Return",
        "目前持有": "Currently Held By",
        "目前持有人：": "Current Holder:",
        "目前持有人": "Current Holder",
        "持有者": "Holder",
        "擁有者": "Owner",
        "擁有者：%(owner)s": "Owner: %(owner)s",
        
        # User profile
        "個人資料": "Profile",
        "個人": "Personal",
        "使用者資訊": "User Info",
        "用戶資料": "User Data",
        "用戶": "User",
        "成員": "Member",
        "電子信箱": "Email",
        "出生日期": "Date of Birth",
        "用於年齡驗證（需年滿 18 歲）": "For age verification (must be 18+)",
        "您的年齡未滿 18 歲，依法規限制無法註冊使用本服務": "You must be 18+ to register",
        "頭像": "Avatar",
        "%(nickname)s 的頭像": "%(nickname)s's Avatar",
        "%(nickname)s 的 Google 頭像": "%(nickname)s's Google Avatar",
        "Google 頭像": "Google Avatar",
        "未設定暱稱": "Nickname Not Set",
        "預設取書地點": "Default Meetup Location",
        "例如：台北市大安區": "e.g., Da'an District, Taipei",
        "聯絡信箱或網站 URL（mailto: 或 https://）": "Contact email or website URL (mailto: or https://)",
        "加入時間": "Member Since",
        "建立於 %(date)s": "Created %(date)s",
        "您目前持有的書籍": "Books You Currently Hold",
        "您貢獻的書籍": "Books You've Contributed",
        "我的貢獻": "My Contributions",
        "我的書架": "My Bookshelf",
        "我的申訴": "My Appeals",
        "貢獻者": "Contributor",
        "持書人": "Book Holder",
        "持書人頭像": "Holder Avatar",
        "寄件人": "Sender",
        "收件人": "Recipient",
        
        # UI elements
        "首頁": "Home",
        "探索": "Explore",
        "書架": "Bookshelf",
        "選單": "Menu",
        "主選單": "Main Menu",
        "關閉選單": "Close Menu",
        "返回": "Back",
        "返回首頁": "Back to Home",
        "返回交易列表": "Back to Deal List",
        "前往": "Go",
        "取消": "Cancel",
        "確認": "Confirm",
        "確定": "OK",
        "標題": "Title",
        "主體": "Body",
        "描述": "Description",
        "狀態": "Status",
        "狀態更新": "Status Updated",
        "附加資料": "Attachments",
        "證據文件": "Evidence Documents",
        "來源": "Source",
        "操作": "Actions",
        "下載我的資料": "Download My Data",
        "關於與幫助": "About & Help",
        "了解運作機制": "How It Works",
        "運作機制": "How It Works",
        
        # Welcome / Landing
        "Exbooks 共享書籍": "Exbooks — Community Book Sharing",
        "Exbooks 共享書籍 v1.0": "Exbooks v1.0",
        "Exbooks 共享書籍 - 讓好書自由流動": "Exbooks — Let Good Books Flow Freely",
        "Exbooks - 未來感共享體驗": "Exbooks — Futuristic Sharing Experience",
        "公益性質的去中心化書籍共享社群": "A non-profit, decentralized book sharing community",
        "為什麼選擇 Exbooks？": "Why Exbooks?",
        "打破傳統借閱限制，建立以信任為基礎的書籍共享生態系。": "Breaking traditional borrowing limits to build a trust-based book sharing ecosystem.",
        "簡單四個步驟，開啟你的書籍共享旅程": "Four simple steps to start your book sharing journey",
        "準備好開始您的閱讀旅程了嗎？": "Ready to start your reading journey?",
        "立即加入": "Join Now",
        "讓好書": "Let Good Books",
        "讓知識流動。": "Let Knowledge Flow.",
        "加入我們，讓閒置的書籍發揮最大價值，遇見更多同樣熱愛閱讀的朋友。": "Join us — give idle books new life and meet fellow book lovers.",
        "去中心化管理": "Decentralized Management",
        "雙軌流通模式": "Dual Circulation Model",
        "知識無界限": "Knowledge Without Borders",
        "新會員": "New Member",
        "新手": "Beginner",
        "新手任務": "Beginner Tasks",
        "新手暫無編輯權限": "Beginners cannot edit yet",
        "新手等級尚無編輯權限": "Beginner level has no edit permissions",
        "開發中": "Under Development",
        
        # Stats
        "出借次數": "Times Lent",
        "成功歸還次數": "Successful Returns",
        "活動統計": "Activity Stats",
        "摘要指標": "Summary Metrics",
        "共 ": "Total: ",
        " %(counter)s 本書籍": "%(counter)s books",
        "有 %(count)s 本書已逾期": "%(count)s books overdue",
        " %(count)s 筆": "%(count)s entries",
        "今日剩餘 <span id=\"remaining-exports\">--</span> 次": "Remaining today: <span id=\"remaining-exports\">--</span>",
        
        # Footer / status
        "您還沒有已完成的交易記錄": "No completed deals yet",
        "您還沒有待對方回應的交易申請": "No pending deal requests",
        "您還沒有建立任何套書": "No book sets created yet",
        "目前沒有待處理的交易": "No pending deals",
        "目前沒有待評價的交易": "No deals awaiting rating",
        "目前沒有約定面交的交易": "No scheduled meetups",
        "目前沒有資料": "No data available",
        "目前無法申請交易": "Cannot request a deal at this time",
        "等待收書方確認歸還或雙方先完成互評": "Awaiting the borrower to confirm return or both parties to rate each other",
        "尚未評價": "Not Yet Rated",
        "全部流通性": "All Availability",
        "接收者": "Receiver",
        "回應者": "Respondent",
        "回應者已評價": "Respondent Rated",
        "申請者已評價": "Applicant Rated",
        "申請者取消": "Cancelled by Applicant",
        "已回應": "Responded",
        "交易接受": "Deal Accepted",
        "交易婉拒": "Deal Declined",
        "交易已被回應": "Deal Has Been Responded To",
        
        # Error / misc
        "請修正以下錯誤：": "Please correct the following errors:",
        "請稍候": "Please wait…",
        "登出": "Log Out",
        "登入 / 註冊": "Log In / Register",
        "帳號已禁用": "Account Disabled",
        "錯誤": "Error",
        "發生錯誤": "An error occurred",
        "成功": "Success",
        "新增成功": "Added successfully",
        "更新成功": "Updated successfully",
        "刪除成功": "Deleted successfully",
        "以電子郵件寄送": "Send via Email",
        "複製分享網址": "Copy Share URL",
        "電腦": "Computer",
        "手機": "Mobile",
        "平板": "Tablet",
        "徽章圖標": "Badge Icon",
        "CSS class 或圖片路徑": "CSS class or image path",
        "空白": "Blank",
        "（可選）": "(Optional)",
        "（必填）": "(Required)",
        "無資料": "No Data",
        "載入中…": "Loading…",
        "處理中…": "Processing…",
        
        # Messages/notifications
        "交易抱怨": "Deal Complaint",
        "交易訊息": "Deal Message",
        "系統": "System",
        "管理員": "Admin",
        "自動": "Auto",
        "尚未設定": "Not Set",
        "未指定": "Not Specified",
        "無": "None",
        
        # Email verification
        "我們已寄出一封確認信。請至您的電子信箱點擊連結以完成註冊流程。": "We've sent a confirmation email. Click the link to complete your registration.",
        "確認電子信箱": "Confirm Email",
        "重寄確認信": "Resend Confirmation",
        
        # Alert
        "確認信箱": "Email Confirmation",
        "密碼重設": "Password Reset",
        "安全性": "Security",
        
        # Search result page info
        "搜尋結果": "Search Results",
        "找到 %(count)s 筆結果": "Found %(count)s results",
        "顯示 %(start)s - %(end)s，共 %(total)s 筆": "Showing %(start)s–%(end)s of %(total)s",
      
        # Deal list
        "對 %(nickname)s 的評價": "Rating for %(nickname)s",
        "關於 %(nickname)s 的評價": "Ratings about %(nickname)s",
        "來自 %(nickname)s 的評價": "Rating from %(nickname)s",
        
        # Template titles
        "Exbooks - %(title)s": "Exbooks — %(title)s",
        "%(name)s - Exbooks": "%(name)s — Exbooks",
        "Exbooks - 交易管理": "Exbooks — Deal Management",
        "Exbooks - 交易詳情": "Exbooks — Deal Details",
        "Exbooks - 新增書籍": "Exbooks — Add Book",
        "Exbooks - 編輯書籍": "Exbooks — Edit Book",
        "Exbooks - 所有書籍": "Exbooks — All Books",
        "Exbooks - 個人資料": "Exbooks — Profile",
        "Exbooks - 編輯個人資料": "Exbooks — Edit Profile",
        "Exbooks - 我的書架": "Exbooks — My Bookshelf",
        "Exbooks - 我的申訴": "Exbooks — My Appeals",
        "Exbooks - 申訴詳情": "Exbooks — Appeal Details",
        "Exbooks - 申請交易": "Exbooks — Request Deal",
        "Exbooks - 願望書車": "Exbooks — Wishlist",
        "我的套書 - Exbooks": "My Book Sets — Exbooks",
        
        # app strings
        "等待中": "Pending",
        "可借用": "Available for Borrow",
        "可預約": "Available for Reservation",
        "已預約": "Reserved",
        "不可借用": "Not Available",
        "下載中": "Downloading",
        "下載完成": "Download Complete",
        "上傳中": "Uploading",
        "上傳完成": "Upload Complete",
        "備份": "Backup",
        "還原": "Restore",
        "匯出": "Export",
        "匯入": "Import",
        "是否停權中": "Is Suspended",
        "停權結束時間": "Suspension End Time",
        "暫時停權的結束時間，null 表示永久停權": "End time of temporary suspension (null = permanent)",
        "停權原因": "Suspension Reason",
        "已損毀": "Damaged",
        "競價替代取消（BR-15）": "Bid Replacement Cancellation (BR-15)",
        "申請狀態": "Application Status",
        "是否啟用": "Enabled",
        "繁體中文": "Traditional Chinese",
        "請確認 <span class=\"font-semibold text-slate-900\">%(email)s</span> ": "Please confirm <span class=\"font-semibold text-slate-900\">%(email)s</span> ",
        "此確認連結已過期或無效。請 <a href=\"%(email_url)s\" class=\"text-primary ": "This confirmation link has expired or is invalid. Please <a href=\"%(email_url)s\" class=\"text-primary ",
        "編輯個人資料": "Edit Profile",
        "%(counter)s 本書籍": "%(counter)s books",
        " 本": " volumes",
        " 筆": " entries",
        "沒有實體圖書館，每一位社員都是圖書管理員。拿出你的閒置藏書，與熱愛閱讀的朋友交換，建立互信的閱讀社群。": "No physical library — every member is a librarian. Share idle books with fellow readers and build a trusted reading community.",
        "不再依賴中央圖書館，書籍由擁有者自行保管或在社群間流傳，實現真正的共享經濟。": "No central library — books are kept by owners or circulate within the community, enabling true sharing economy.",
        "自由設定書籍為「開放傳遞」讓書持續漂流，或「閱畢即還」確保愛書回到身邊。": "Set books to 'Open Transfer' for ongoing circulation or 'Return After Reading' to ensure they come back.",
        "面交後雙方互評誠信、準時與書況，累積社群信用，確保每一次借閱都令人安心。": "Rate each other on trust, punctuality, and book condition to build community credit for worry-free borrowing.",
        "輸入 ISBN 或書名，設定流通方式（開放傳遞/閱畢即還）與可面交時間地點，將愛書分享給社群。": "Enter ISBN or title, set availability type and meetup details, then share your book with the community.",
        "探索與申請": "Discover & Request",
        "在平台上尋找感興趣的書籍，發送借閱申請並與書籍目前的持有者確認面交細節。": "Find books you love, send a borrow request, and arrange a meetup with the current holder.",
        "針對此次交易的友善度、準時度與書況準確度給予評價，共同維護高品質的共享環境。": "Rate friendliness, punctuality, and condition accuracy to maintain a high-quality sharing environment.",
        "書籍遺失、損毀或尋獲": "Book Lost, Damaged, or Found",
        "確認面交完成？\\\\n\\\\n確認後交易將進入「已面交」狀態，雙方可以開始互評。": "Confirm meetup complete?\\n\\nThe deal will enter 'Met Up' status and both parties can start rating.",
        "注意：雙方尚未完成互評。如果您已收到書籍，可以強制確認歸還，但這將無法獲得完整的信用積分。確定要繼續嗎？": "Note: Both parties haven't rated yet. You can force-confirm return, but won't receive full trust score. Continue?",
        "%(count)s 筆": "%(count)s entries",
        "可信": "Trustworthy",
        "優良": "Excellent",
    }
    
    if text in translations:
        return translations[text]
    
    # Fallback: if the string has no Chinese characters, return as-is
    if not re.search(r'[\u4e00-\u9fff]', text):
        return text
    
    # Otherwise, generate a basic English version
    return f"[TBD] {text}"


def fill_english():
    """Translate Chinese msgid to English msgstr."""
    po = polib.pofile(EN_PO)
    count = 0
    skipped = 0
    for entry in po:
        if not entry.msgid:
            continue
        if entry.msgstr:
            skipped += 1
            continue
        translation = translate_chinese_to_english(entry.msgid)
        entry.msgstr = translation
        count += 1
    po.save()
    print(f"en: translated {count} strings ({skipped} already had translations)")


def translate_chinese_to_korean(text: str) -> str:
    """Translate a Chinese string to Korean using dictionary."""
    # Exact-match only for brand/text prefixes: still look up full string in dictionary
    # (Don't early-return — Chinese portion after prefix needs translation)
    if text.startswith("User"):
        return text
    if text.startswith("Back to"):
        return text
    if text == "English":
        return "English"
    if text == "Email":
        return "이메일"
    if text == "Confirm":
        return "확인"
    if text == "ISBN":
        return "ISBN"
    if text == "Sign In":
        return "로그인"
    if text == "Sign Up":
        return "회원가입"
    if text == "Social Network Login Failure":
        return text
    if "Confirmation" in text or "Verify" in text:
        return text

    ko_translations = {
        # Login / Registration
        "Email": "이메일",
        "密碼": "비밀번호",
        "登入": "로그인",
        "暱稱": "닉네임",
        "顯示在平台上的名稱": "표시 이름",
        "出生日期": "생년월일",
        "用於年齡驗證（需年滿 18 歲）": "연령 확인용 (만 18세 이상 필수)",
        "再次確認密碼": "비밀번호 확인",
        "你的暱稱": "닉네임",
        "註冊": "가입",
        "預設取書地點": "기본 만남 장소",
        "例如：台北市大安區": "예: 대만 타이베이시 다안구",
        "完成註冊": "가입 완료",
        "儲存並繼續": "저장 후 계속",
        "完善個人資料": "프로필 작성",
        "立即免費註冊": "지금 무료 가입",
        # Common UI
        "繁體中文": "繁體中文",
        "首頁": "홈",
        "書架": "책장",
        "交易": "거래",
        "通知": "알림",
        "個人": "내 정보",
        "通知中心": "알림 센터",
        "交易紀錄": "거래 내역",
        "設定": "설정",
        "關於與幫助": "정보 및 도움말",
        "開發中": "개발 중",
        "登出": "로그아웃",
        "登入 / 註冊": "로그인 / 가입",
        "返回": "뒤로",
        "取消": "취소",
        "確認": "확인",
        "確定": "확인",
        "儲存變更": "변경사항 저장",
        "編輯": "편집",
        "刪除": "삭제",
        "搜尋": "검색",
        "全部分類": "전체 카테고리",
        "全部流通性": "전체 이용 가능성",
        "所有書籍": "모든 책",
        "新增書籍": "책 추가",
        "分享書籍": "책 공유",
        "上架閒置書籍": "책 등록",
        "開始探索書籍": "탐색 시작",
        "探索社群好書": "커뮤니티 책 탐색",
        "加入時間": "가입일",
        "下載我的資料": "내 데이터 다운로드",
        "個人資料": "프로필",
        "編輯個人資料": "프로필 편집",
        "帳號設定": "계정 설정",
        # Welcome / Landing
        "Exbooks 共享書籍": "Exbooks 책 공유",
        "Exbooks 共享書籍 v1.0": "Exbooks v1.0",
        "Exbooks 共享書籍 - 讓好書自由流動": "Exbooks — 좋은 책이 자유롭게 흐르도록",
        "Exbooks - 未來感共享體驗": "Exbooks — 미래형 공유 경험",
        "公益性質的去中心化書籍共享社群": "비영리 분산형 책 공유 커뮤니티",
        "為什麼選擇 Exbooks？": "왜 Exbooks인가요?",
        "打破傳統借閱限制，建立以信任為基礎的書籍共享生態系。": "전통적인 대출 제한을 깨고 신뢰 기반의 책 공유 생태계를 구축합니다.",
        "簡單四個步驟，開啟你的書籍共享旅程": "네 가지 간단한 단계로 책 공유 여정 시작",
        "準備好開始您的閱讀旅程了嗎？": "독서 여정을 시작할 준비가 되셨나요?",
        "立即加入": "지금 가입",
        "讓好書": "좋은 책이",
        "讓知識流動。": "지식이 흐르게 하세요.",
        "加入我們，讓閒置的書籍發揮最大價值，遇見更多同樣熱愛閱讀的朋友。": "함께해요 — 쉬고 있는 책에 새 생명을 불어넣고 책을 사랑하는 사람들을 만나보세요.",
        "去中心化管理": "분산형 관리",
        "雙軌流通模式": "이중 유통 모델",
        "知識無界限": "지식에는 경계가 없습니다",
        "新會員": "새 회원",
        "新手": "초보자",
        "新手任務": "초보자 미션",
        "新手暫無編輯權限": "초보자는 편집 권한이 없습니다",
        "新手等級尚無編輯權限": "초보자 레벨은 편집 권한이 없습니다",
        "自由流通": "자유 유통",
        "Exbooks - %(title)s": "Exbooks — %(title)s",
        "%(name)s - Exbooks": "%(name)s — Exbooks",
        "Exbooks - 交易管理": "Exbooks — 거래 관리",
        "Exbooks - 交易詳情": "Exbooks — 거래 상세",
        "Exbooks - 新增書籍": "Exbooks — 책 추가",
        "Exbooks - 編輯書籍": "Exbooks — 책 편집",
        "Exbooks - 所有書籍": "Exbooks — 모든 책",
        "Exbooks - 個人資料": "Exbooks — 프로필",
        "Exbooks - 編輯個人資料": "Exbooks — 프로필 편집",
        "Exbooks - 我的書架": "Exbooks — 내 책장",
        "Exbooks - 我的申訴": "Exbooks — 내 이의신청",
        "Exbooks - 申訴詳情": "Exbooks — 이의신청 상세",
        "Exbooks - 申請交易": "Exbooks — 거래 요청",
        "Exbooks - 願望書車": "Exbooks — 위시리스트",
        "我的套書 - Exbooks": "내 책 세트 — Exbooks",
        # Books
        "書籍": "책",
        "書籍簡介": "책 소개",
        "書籍詳情": "책 상세",
        "書名": "제목",
        "作者": "저자",
        "作者（正規化）": "저자 (정규화)",
        "出版社": "출판사",
        "出版社（正規化）": "출판사 (정규화)",
        "譯者": "번역자",
        "ISBN": "ISBN",
        "10 碼或 13 碼 ISBN": "10자리 또는 13자리 ISBN",
        "分類": "카테고리",
        "小說": "소설",
        "科學": "과학",
        "科技": "기술",
        "藝術": "예술",
        "文學": "문학",
        "歷史": "역사",
        "哲學": "철학",
        "一般": "일반",
        "未分類": "미분류",
        "封面圖片": "표지 이미지",
        "預設封面": "기본 표지",
        "書況描述": "상태 설명",
        "書況照片": "상태 사진",
        "流通性": "이용 가능성",
        "預設流通性": "기본 이용 가능성",
        "開放傳遞": "개방 전달",
        "閱畢即還": "읽고 반납",
        "可移轉": "양도 가능",
        "自由流通": "자유 유통",
        "無借閱限制": "대출 제한 없음",
        "暫不開放": "이용 불가",
        "目前尚未上傳書況照片。": "상태 사진이 아직 업로드되지 않았습니다.",
        "狀態：": "상태:",
        "上架時間": "등록일",
        "上架第一本書": "첫 번째 책 등록",
        "新增分享書籍": "공유 책 추가",
        "貢獻書籍": "책 기여",
        "探索": "탐색",
        "新視界": "새로운 시야",
        "搜尋 ISBN、書名、作者、出版社": "ISBN, 제목, 저자, 출판사 검색",
        "搜尋書籍": "책 검색",
        "查詢中…": "검색 중…",
        "排序": "정렬",
        "排序鍵": "정렬 키",
        "空白時以顯示名稱小寫排序": "비어있을 때 표시 이름 소문자로 정렬",
        "顯示名稱": "표시 이름",
        "名稱": "이름",
        "刪除書籍": "책 삭제",
        "確定要刪除這本書嗎？此操作無法復原。": "이 책을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
        "確定要刪除這張照片嗎？": "이 사진을 삭제하시겠습니까?",
        "編輯書籍資訊": "책 정보 편집",
        "查看書籍詳情": "책 상세 보기",
        "上傳照片": "사진 업로드",
        "照片": "사진",
        "照片說明": "사진 설명",
        "上傳者": "업로드한 사람",
        "分享失敗，請手動複製網址": "공유 실패, URL을 수동으로 복사하세요",
        "已複製分享連結": "공유 링크 복사됨",
        "我想分享這本書給你：%(title)s": "이 책을 공유합니다: %(title)s",
        # Book Set
        "套書": "책 세트",
        "套書名稱": "책 세트 이름",
        "套書說明": "설명",
        "套書書籍 <span class=\"text-primary ml-1\">(%(count)s)</span>": "세트 내 책 <span class=\"text-primary ml-1\">(%(count)s권)</span>",
        "建立套書": "책 세트 만들기",
        "管理套書": "책 세트 관리",
        "我的套書": "내 책 세트",
        "此書籍為套書的一部分，借閱時需整套借出": "이 책은 세트의 일부입니다. 세트 전체를 함께 대출해야 합니다",
        "所屬套書": "세트 소속",
        "最多借 %(max_books)s 本，最長 %(max_days)s 天": "최대 %(max_books)s권, %(max_days)s일",
        "最大借閱天數": "최대 대출 일수",
        "最大持書數量": "최대 보유 권수",
        # Wishlist
        "願望書車": "위시리스트",
        "願望清單": "위시리스트",
        "願望書籍已可借閱": "위시리스트 책을 대출할 수 있습니다",
        "想看什麼書？": "어떤 책을 찾으시나요?",
        # Deal / Trading
        "交易管理": "거래 관리",
        "交易詳情": "거래 상세",
        "交易申請": "거래 요청",
        "交易狀態": "거래 상태",
        "交易狀態進度": "거래 상태 진행",
        "交易類別": "거래 유형",
        "交易類型": "거래 유형",
        "交易夥伴": "거래 파트너",
        "交易書籍": "거래 책",
        "交易留言": "거래 메시지",
        "交易結案": "거래 종료",
        "交易結案（DONE）": "거래 종료 (완료)",
        "交易被取消": "거래 취소됨",
        "交易與信用統計": "거래 및 신뢰도 통계",
        "交易前書籍狀態": "거래 전 책 상태",
        "接受申請": "요청 수락",
        "婉拒": "거절",
        "申請交易": "거래 요청",
        "申請借用": "대출 요청",
        "申請傳遞": "전달 요청",
        "申請回歸": "반납 요청",
        "申請返還": "반환 요청",
        "申請者": "신청자",
        "申請資訊": "신청 정보",
        "申請須知": "신청 안내",
        "申請取消": "요청 취소",
        "取消借閱申請": "대출 요청 취소",
        "申請例外處理": "예외 처리 요청",
        "例外狀況": "예외",
        "例外處理": "예외 처리",
        "例外處理 (EX)": "예외 처리 (EX)",
        "提交申請後，持書人將收到通知": "제출 후 책 보유자가 알림을 받게 됩니다",
        "想跟對方說什麼？": "상대방에게 전할 메시지",
        "對方接受後，您可與持書人協商面交時間地點": "수락 후 책 보유자와 만남 장소와 시간을 협의할 수 있습니다",
        "同一本書的多筆申請": "같은 책에 대한 여러 신청",
        "需要您處理的申請": "처리해야 할 신청",
        "進行中的請求": "진행 중인 요청",
        "有 %(count)s 本書籍收到多筆申請，建議檢視後一併處理": "%(count)s권의 책에 여러 신청이 있습니다 — 함께 검토 후 처리하세요",
        "送出申請": "신청 제출",
        "新增申請": "새 요청",
        "查看資料": "프로필 보기",
        "前往評價": "평가하기",
        "完成交易": "거래 완료",
        "完成交易進度": "거래 진행 상황",
        "確認新增": "추가 확인",
        "確認歸還／上架": "반납/재등록 확인",
        "確認歸還並重新上架": "반납 및 재등록 확인",
        "確認面交完成": "만남 완료 확인",
        "面交完成": "만남 완료",
        "面交完成，請評價": "만남 완료 — 평가해주세요",
        # Deal status
        "已請求": "요청됨",
        "已回應": "응답됨",
        "已面交": "만남 완료",
        "已結案": "종료됨",
        "已取消": "취소됨",
        "已完成": "완료됨",
        "已拒絕": "거절됨",
        "已核准": "승인됨",
        "已通過": "승인됨",
        "已駁回": "기각됨",
        "已提交": "제출됨",
        "已毀損": "손상됨",
        "已遺失": "분실됨",
        "已逾期": "연체",
        "已讀": "읽음",
        "待評價": "평가 대기",
        "待回應": "응답 대기",
        "待審核": "검토 대기",
        "待面交": "만남 대기",
        "待對方回應": "상대방 응답 대기",
        "已被預約": "예약됨",
        "進行中": "진행 중",
        "未知": "알 수 없음",
        "面交地點": "만남 장소",
        "面交時間": "만남 시간",
        "預計借閱天數：%(days)s 天": "예상 대출 기간: %(days)s일",
        "天": "일",
        "本": "권",
        "最少 15 天，最多 90 天": "최소 15일, 최대 90일",
        "最少 7 天，最多 30 天": "최소 7일, 최대 30일",
        "取書地點": "수령 장소",
        "可取書時間": "수령 가능 시간",
        # Deal types
        "借用交易": "대출 거래",
        "借用交易 (LN)": "대출 거래 (LN)",
        "借閱中": "대출 중",
        "借閱天數": "대출 일수",
        "借閱次數": "대출 횟수",
        "借閱書籍，閱畢後歸還給持書人": "책을 빌리고 읽은 후 보유자에게 반납",
        "傳遞交易": "전달 거래",
        "傳遞交易 (TF)": "전달 거래 (TF)",
        "回歸交易": "반납 거래",
        "回歸交易 (RG)": "반납 거래 (RG)",
        "返還交易": "반환 거래",
        "返還交易 (RS)": "반환 거래 (RS)",
        "僅 LN/TF 類型交易需要": "LN/TF 유형 거래에만 필요",
        "若為套書交易，關聯至套書": "책 세트 거래인 경우 세트에 연결",
        # Deal process
        "線下面交": "대면 만남",
        "雙方在約定的時間地點碰面交書。確認書況無誤後，在平台上點擊「已面交」。": "약속한 시간과 장소에서 만나 책을 전달합니다. 책 상태를 확인한 후 플랫폼에서 '만남 완료'를 클릭하세요.",
        "面交時請確認書況，並在系統中完成確認": "만남 시 책 상태를 확인하고 시스템에서 확인하세요",
        "面交時拍攝的照片關聯至交易": "만남 시 촬영한 사진이 거래에 연결됩니다",
        "留言溝通": "메시지 보내기",
        "發送訊息": "메시지 전송",
        "歷史留言紀錄": "메시지 내역",
        "輸入訊息": "메시지 입력…",
        "訊息內容": "메시지 내용",
        "相關書籍": "관련 책",
        "相關交易": "관련 거래",
        # Rating
        "評價": "평가",
        "給出評價": "평가 남기기",
        "評價送出": "평가 제출됨",
        "評價爭議": "평가 이의제기",
        "評價者": "평가자",
        "被評價者": "평가 대상자",
        "評語": "코멘트",
        "雙方完成互評": "양측 평가 완료",
        "雙向評價": "양방향 평가",
        "提示：待雙方評價完成後，主按鈕才會開啟": "참고: 양측 평가 완료 후 메인 버튼이 활성화됩니다",
        "提示：即便對方尚未評價，主人仍可先點擊下方「確認歸還」。": "참고: 상대방이 아직 평가하지 않았어도 먼저 '반납 확인'을 클릭할 수 있습니다",
        "平均評價": "평균 평점",
        "友善評分": "친절도 점수",
        "書況準確度評分": "책 상태 정확도 점수",
        "準時評分": "정시성 점수",
        # Overdue
        "逾期次數": "연체 횟수",
        "逾期爭議": "연체 이의제기",
        "逾期處理": "연체 처리",
        "到期日": "마감일",
        "書籍即將到期": "책 대출 만료 임박",
        "書籍已逾期": "책 연체",
        "到期排程處理": "예정된 연체 처리",
        "公開逾期名單": "공개 연체 명단",
        "強制確認歸還": "강제 반납 확인",
        # Extension
        "延期申請紀錄": "연장 요청 내역",
        "延長申請": "연장 요청",
        "延長核准": "연장 승인",
        "延長拒絕": "연장 거절",
        "延長取消": "연장 취소",
        "延長申請已核准": "연장 승인됨",
        "延長申請已拒絕": "연장 거절됨",
        "延長天數": "연장 일수",
        "可延長天數": "허용 연장 일수",
        # Exchange event
        "交換事件": "교환 이벤트",
        "事件類型": "이벤트 유형",
        "持有者變更": "보유자 변경",
        "歸還書籍給貢獻者": "기여자에게 책 반납",
        "主人確認歸還書籍": "소유자 반납 확인",
        "貢獻者取回書籍": "기여자 책 회수",
        "強制確認歸還": "강제 반납 확인",
        "書籍傳遞給下一位讀者": "다음 독자에게 책 전달",
        "確認歸還並重新上架": "반납 확인 및 재등록",
        "應返還": "반납 예정",
        "目前持有": "현재 보유",
        "目前持有人：": "현재 보유자:",
        "目前持有人": "현재 보유자",
        "持有者": "보유자",
        "擁有者": "소유자",
        "擁有者：%(owner)s": "소유자: %(owner)s",
        # User profile
        "使用者資訊": "사용자 정보",
        "用戶資料": "사용자 데이터",
        "用戶": "사용자",
        "成員": "회원",
        "電子信箱": "이메일",
        "您的年齡未滿 18 歲，依法規限制無法註冊使用本服務": "만 18세 이상만 가입할 수 있습니다",
        "頭像": "아바타",
        "%(nickname)s 的頭像": "%(nickname)s의 아바타",
        "%(nickname)s 的 Google 頭像": "%(nickname)s의 Google 아바타",
        "Google 頭像": "Google 아바타",
        "未設定暱稱": "닉네임 미설정",
        "聯絡信箱或網站 URL（mailto: 或 https://）": "연락처 이메일 또는 웹사이트 URL (mailto: 또는 https://)",
        "建立於 %(date)s": "%(date)s에 가입",
        "您目前持有的書籍": "현재 보유 중인 책",
        "您貢獻的書籍": "기여한 책",
        "我的貢獻": "내 기여",
        "我的書架": "내 책장",
        "我的申訴": "내 이의신청",
        "貢獻者": "기여자",
        "持書人": "책 보유자",
        "持書人頭像": "보유자 아바타",
        "寄件人": "발신자",
        "收件人": "수신자",
        "接收者": "수신자",
        "回應者": "응답자",
        "回應者已評價": "응답자 평가함",
        "申請者已評價": "신청자 평가함",
        "申請者取消": "신청자 취소",
        "已回應": "응답됨",
        "交易接受": "거래 수락",
        "交易婉拒": "거래 거절",
        "交易已被回應": "거래에 응답됨",
        # UI elements
        "選單": "메뉴",
        "主選單": "메인 메뉴",
        "關閉選單": "메뉴 닫기",
        "返回首頁": "홈으로",
        "返回交易列表": "거래 목록으로",
        "前往": "이동",
        "標題": "제목",
        "主體": "본문",
        "描述": "설명",
        "狀態": "상태",
        "狀態更新": "상태 업데이트",
        "附加資料": "첨부 파일",
        "證據文件": "증빙 문서",
        "來源": "출처",
        "操作": "작업",
        "關於與幫助": "정보 및 도움말",
        "了解運作機制": "작동 방식 알아보기",
        "運作機制": "작동 방식",
        # Error / misc
        "請修正以下錯誤：": "다음 오류를 수정하세요:",
        "請稍候": "잠시만 기다려주세요…",
        "錯誤": "오류",
        "發生錯誤": "오류 발생",
        "成功": "성공",
        "新增成功": "추가 성공",
        "更新成功": "업데이트 성공",
        "刪除成功": "삭제 성공",
        "以電子郵件寄送": "이메일로 전송",
        "複製分享網址": "공유 URL 복사",
        "電腦": "컴퓨터",
        "手機": "모바일",
        "平板": "태블릿",
        "徽章圖標": "배지 아이콘",
        "CSS class 或圖片路徑": "CSS 클래스 또는 이미지 경로",
        "空白": "공백",
        "（可選）": "(선택사항)",
        "（必填）": "(필수)",
        "無資料": "데이터 없음",
        "載入中…": "로딩 중…",
        "處理中…": "처리 중…",
        "尚未設定": "설정되지 않음",
        "未指定": "지정되지 않음",
        "無": "없음",
        "是": "예",
        "否": "아니오",
        # Messages/notifications
        "交易抱怨": "거래 불만",
        "交易訊息": "거래 메시지",
        "系統": "시스템",
        "管理員": "관리자",
        "自動": "자동",
        # Email
        "我們已寄出一封確認信。請至您的電子信箱點擊連結以完成註冊流程。": "확인 이메일을 보냈습니다. 이메일의 링크를 클릭하여 가입을 완료하세요.",
        "確認電子信箱": "이메일 확인",
        "重寄確認信": "확인 메일 재전송",
        # Violation types
        "輕微": "경미",
        "中等": "중간",
        "嚴重": "심각",
        "警告": "경고",
        "暫時停權": "임시 정지",
        "永久停權": "영구 정지",
        "未依約定面交": "만남 불이행",
        "延遲歸還": "지연 반납",
        "書況描述不符": "책 상태 불일치",
        "無正當理由取消": "정당한 사유 없는 취소",
        "詐欺": "사기",
        "騷擾": "괴롭힘",
        "惡意破壞": "악의적 손상",
        "冒用身份": "신원 도용",
        "其他": "기타",
        # Violation management
        "違規用戶": "위반 사용자",
        "處分類型": "처벌 유형",
        "違規等級": "위반 수준",
        "違規行為": "위반 유형",
        "違規描述": "설명",
        "停權天數": "정지 일수",
        "暫時停權時必填，7-30 天": "임시 정지 시 필수, 7-30일",
        "是否生效中": "활성",
        "警告永遠生效；停權在期滿或解除後設為 False": "경고는 영구적입니다. 정지는 만료 또는 해제 후 False로 설정",
        "相關申訴": "관련 이의신청",
        "違規次數": "위반 횟수",
        "處分者": "발행자",
        "違規處分": "위반 처벌",
        "限制中": "제한됨",
        "部分功能受限": "일부 기능 제한",
        "等級保護起始時間": "레벨 보호 시작 시간",
        "降級保護週數": "강등 보호 (주)",
        "記錄用戶積分跌破門檻後，降級保護期開始計時的時間點": "점수가 기준 이하로 떨어진 후 강등 보호 기간이 시작된 타임스탬프",
        "達到此等級後的保護期限，期間內若積分不足也不會降級": "이 레벨 도달 후 보호 기간. 점수가 부족해도 강등되지 않음",
        "對應群組名稱": "해당 그룹 이름",
        "等級": "레벨",
        "當下等級（0-3）": "현재 레벨 (0-3)",
        "當下積分": "현재 점수",
        "用戶的信用積分，根據交易、評價、逾期等計算": "거래, 평가, 연체 기록 등을 기반으로 계산된 사용자 신뢰 점수",
        "用戶目前是否處於停權狀態": "사용자가 현재 정지 상태인지 여부",
        "最低信用等級": "최소 신뢰 레벨",
        "最低積分門檻": "최소 점수 기준",
        "申請者信用等級需達 0-3，0 表示不限制": "신청자 신뢰 레벨은 0-3 (0 = 제한 없음)",
        "公式版本": "공식 버전",
        "基準": "기준",
        "批次／手動重算": "일괄/수동 재계산",
        "詳情": "상세",
        "解除時間": "해제 시간",
        "解除者": "해제자",
        "信用積分": "신뢰 점수",
        "信用積分稽核": "신뢰 점수 감사",
        "信用等級配置": "신뢰 레벨 설정",
        "信用評價機制": "신뢰 및 평가 시스템",
        "角色": "역할",
        "操作者": "운영자",
        "平均評價": "평균 평점",
        "可信": "신뢰할 수 있음",
        "優良": "우수",
        "違規次數": "위반 횟수",
        "出借次數": "대출 횟수",
        "成功歸還次數": "성공적 반납 횟수",
        "活動統計": "활동 통계",
        "摘要指標": "요약 지표",
        "共 ": "총 ",
        " %(counter)s 本書籍": "%(counter)s권의 책",
        "有 %(count)s 本書已逾期": "%(count)s권 연체",
        " %(count)s 筆": "%(count)s건",
        "今日剩餘 <span id=\"remaining-exports\">--</span> 次": "오늘 남은 횟수: <span id=\"remaining-exports\">--</span>",
        # Footer / status
        "您還沒有已完成的交易記錄": "완료된 거래가 없습니다",
        "您還沒有待對方回應的交易申請": "대기 중인 거래 요청이 없습니다",
        "您還沒有建立任何套書": "생성된 책 세트가 없습니다",
        "目前沒有待處理的交易": "처리할 거래가 없습니다",
        "目前沒有待評價的交易": "평가할 거래가 없습니다",
        "目前沒有約定面交的交易": "예정된 만남이 없습니다",
        "目前沒有資料": "데이터가 없습니다",
        "目前無法申請交易": "현재 거래를 요청할 수 없습니다",
        "等待收書方確認歸還或雙方先完成互評": "수취인의 반납 확인 또는 양측의 상호 평가를 기다리는 중",
        "尚未評價": "아직 평가되지 않음",
        "下載中": "다운로드 중",
        "下載完成": "다운로드 완료",
        "上傳中": "업로드 중",
        "上傳完成": "업로드 완료",
        "備份": "백업",
        "還原": "복원",
        "匯出": "내보내기",
        "匯入": "가져오기",
        "是否停權中": "정지 상태",
        "停權結束時間": "정지 종료 시간",
        "暫時停權的結束時間，null 表示永久停權": "임시 정지 종료 시간 (null = 영구 정지)",
        "停權原因": "정지 사유",
        "競價替代取消（BR-15）": "경매 대체 취소 (BR-15)",
        "申請狀態": "신청 상태",
        "是否啟用": "활성화",
        "請確認 <span class=\"font-semibold text-slate-900\">%(email)s</span> 是您帳號的電子郵件地址。": "<span class=\"font-semibold text-slate-900\">%(email)s</span>이(가) 귀하의 이메일 주소인지 확인해주세요.",
        "此確認連結已過期或無效。請 <a href=\"%(email_url)s\" class=\"text-primary underline\">重新申請驗證連結</a>。": "이 확인 링크는 만료되었거나 유효하지 않습니다. <a href=\"%(email_url)s\" class=\"text-primary underline\">새 인증 링크 요청</a>",
        "%(counter)s 本書籍": "%(counter)s권의 책",
        " 本": " 권",
        " 筆": " 건",
        "沒有實體圖書館，每一位社員都是圖書管理員。拿出你的閒置藏書，與熱愛閱讀的朋友交換，建立互信的閱讀社群。": "물리적 도서관은 없습니다 — 모든 회원이 사서입니다. 쉬고 있는 책을 독서 애호가들과 공유하고 신뢰 기반의 독서 커뮤니티를 구축하세요.",
        "不再依賴中央圖書館，書籍由擁有者自行保管或在社群間流傳，實現真正的共享經濟。": "중앙 도서관이 없습니다 — 책은 소유자가 보관하거나 커뮤니티 내에서 유통되며 진정한 공유 경제를 실현합니다.",
        "自由設定書籍為「開放傳遞」讓書持續漂流，或「閱畢即還」確保愛書回到身邊。": "책을 '개방 전달'로 설정하여 지속적인 유통을 하거나 '읽고 반납'으로 설정하여 책이 돌아오도록 할 수 있습니다.",
        "面交後雙方互評誠信、準時與書況，累積社群信用，確保每一次借閱都令人安心。": "만남 후 신뢰도, 정시성, 책 상태를 상호 평가하여 커뮤니티 신뢰를 쌓고 안심하고 대출할 수 있습니다.",
        "輸入 ISBN 或書名，設定流通方式（開放傳遞/閱畢即還）與可面交時間地點，將愛書分享給社群。": "ISBN 또는 제목을 입력하고 이용 가능성 유형과 만남 세부정보를 설정한 후 커뮤니티와 책을 공유하세요.",
        "探索與申請": "탐색 및 요청",
        "在平台上尋找感興趣的書籍，發送借閱申請並與書籍目前的持有者確認面交細節。": "마음에 드는 책을 찾아 대출 요청을 보내고 현재 보유자와 만남 세부정보를 조율하세요.",
        "針對此次交易的友善度、準時度與書況準確度給予評價，共同維護高品質的共享環境。": "친절도, 정시성, 책 상태 정확도를 평가하여 고품질 공유 환경을 유지하세요.",
        "書籍遺失、損毀或尋獲": "책 분실, 손상 또는 발견",
        "確認面交完成？\\\\n\\\\n確認後交易將進入「已面交」狀態，雙方可以開始互評。": "만남 완료를 확인하시겠습니까?\\n\\n거래가 '만남 완료' 상태로 전환되며 양측이 평가를 시작할 수 있습니다.",
        "注意：雙方尚未完成互評。如果您已收到書籍，可以強制確認歸還，但這將無法獲得完整的信用積分。確定要繼續嗎？": "참고: 양측이 아직 평가를 완료하지 않았습니다. 책을 받았다면 강제 반납 확인이 가능하지만 전체 신뢰 점수를 받을 수 없습니다. 계속하시겠습니까?",
        "An error occurred while attempting to login via your social network account.": "소셜 네트워크 계정으로 로그인하는 중 오류가 발생했습니다.",
        "You decided to cancel logging in with your social network account.": "소셜 네트워크 계정 로그인을 취소했습니다.",
        "Login Cancelled": "로그인 취소됨",
        "Social Network Login Failure": "소셜 네트워크 로그인 실패",

        # Appeal/Review strings
        "審核中": "검토 중",
        "帳號停權申訴": "계정 정지 이의신청",
        "申訴人": "이의신청자",
        "申訴類型": "이의신청 유형",
        "審核備註": "검토 메모",
        "審核者": "검토자",
        "審核時間": "검토 시간",
        "申訴": "이의신청",
        "申訴詳情": "이의신청 상세",
        "審核結果": "검토 결과",
        "取消申訴": "이의신청 취소",
        "尚無申訴紀錄": "이의신청 내역이 없습니다",
        "您尚未提交任何申訴": "아직 이의신청을 제출하지 않았습니다",
        "提交申訴": "이의신청 제출",
        "申訴已送出": "이의신청 제출됨",
        "申訴審核完成": "이의신청 검토 완료",
        "申訴狀態更新": "이의신청 상태 업데이트",
        "由 %(email)s 於 %(date)s 審核": "%(email)s님이 %(date)s에 검토함",

        # Notification strings
        "收到交易申請": "새 거래 요청",
        "收到延長申請": "새 연장 요청",
        "收到新的評價": "새 평가 수신",
        "收到違規處分": "위반 제재 수신",
        "通知類型": "알림 유형",
        "通知標題": "알림 제목",
        "通知訊息": "알림 메시지",
        "是否已讀": "읽음 여부",
        "發送者": "발신자",
        "啟用推播通知": "푸시 알림 활성화",
        "關閉後將不會收到瀏覽器 Push 通知": "비활성화 시 브라우저 푸시 알림을 받지 않습니다",
        "啟用 Email 通知": "이메일 알림 활성화",
        "關閉後將不會收到 Email 通知": "비활성화 시 이메일 알림을 받지 않습니다",
        "收到評價": "평가 수신",

        # Push subscription strings
        "Push 訂閱": "푸시 구독",
        "訂閱端點": "구독 엔드포인트",
        "Push 服務的唯一端點 URL": "푸시 서비스 고유 엔드포인트 URL",
        "p256dh 金鑰": "p256dh 키",
        "用戶端的公開金鑰（ECDH P-256）": "클라이언트 공개 키 (ECDH P-256)",
        "auth 金鑰": "auth 키",
        "認證金鑰（16 bytes base64 編碼）": "인증 키 (16바이트 base64 인코딩)",
        "瀏覽器識別資訊": "브라우저 식별 정보",
        "停用後將不會收到 Push 通知": "비활성화 시 푸시 알림을 받지 않습니다",
        "VAPID 公開金鑰": "VAPID 공개 키",
        "用於前端註冊 Push 訂閱": "프론트엔드 푸시 구독 등록에 사용",
        "VAPID 私有金鑰": "VAPID 비공개 키",
        "用於後端發送 Push 通知（請勿洩漏）": "백엔드 푸시 알림 전송에 사용 (노출 금지)",
        "Web Push 設定": "Web Push 설정",

        # Technical / misc
        "格式: [{\"weekday\": 1, \"start\": \"09:00\", \"end\": \"12:00\"}, ...]": "형식: [{\"weekday\": 1, \"start\": \"09:00\", \"end\": \"12:00\"}, ...]",
        "官方書目": "공식 도서 목록",
        "書目作者關聯": "도서-저자 연결",
        "已損毀": "손상됨",
        "用於取消交易時恢復書籍狀態（BR-14）": "거래 취소 시 책 상태 복원에 사용됨 (BR-14)",
        "帳號已禁用": "계정이 비활성화됨",
        "%(count)s 筆": "%(count)s건",

        # Page title strings (brand name Exbooks preserved)
        "Exbooks 共享書籍": "Exbooks 공유 도서",
        "Exbooks 共享書籍 v1.0": "Exbooks 공유 도서 v1.0",
        "Exbooks 共享書籍 - 讓好書自由流動": "Exbooks 공유 도서 - 좋은 책이 자유롭게 흐르도록",
        "Exbooks - 交易管理": "Exbooks - 거래 관리",
        "Exbooks - 交易詳情": "Exbooks - 거래 상세",
        "Exbooks - 個人資料": "Exbooks - 개인 정보",
        "Exbooks - 編輯個人資料": "Exbooks - 개인 정보 편집",
        "Exbooks - 我的書架": "Exbooks - 내 책장",
        "Exbooks - 我的申訴": "Exbooks - 내 이의신청",
        "Exbooks - 所有書籍": "Exbooks - 모든 책",
        "Exbooks - 新增書籍": "Exbooks - 책 추가",
        "Exbooks - 編輯書籍": "Exbooks - 책 편집",
        "Exbooks - 申請交易": "Exbooks - 거래 신청",
        "Exbooks - 未來感共享體驗": "Exbooks - 미래지향적 공유 경험",
        "Exbooks - 申訴詳情": "Exbooks - 이의신청 상세",
        "Exbooks - 願望書車": "Exbooks - 희망 도서",
        "CSS class 或圖片路徑": "CSS 클래스 또는 이미지 경로",
        "Google 頭像": "Google 프로필 사진",
        "繁體中文": "번체 중국어",
    }

    if text in ko_translations:
        return ko_translations[text]

    # If already has no Chinese characters, return as-is
    if not re.search(r'[\u4e00-\u9fff]', text):
        return text

    # Fallback
    return f"[KO] {text}"


def fill_korean():
    """Translate Chinese msgid to Korean msgstr."""
    po = polib.pofile(KO_PO)
    count = 0
    skipped = 0
    for entry in po:
        if not entry.msgid:
            continue
        if entry.msgstr and entry.msgstr != entry.msgid:
            skipped += 1
            continue
        translation = translate_chinese_to_korean(entry.msgid)
        entry.msgstr = translation
        count += 1
    po.save()
    print(f"ko: translated {count} strings ({skipped} already had translations)")


if __name__ == "__main__":
    fill_zh_hant()
    fill_english()
    fill_korean()
